### PR TITLE
Shrinath/hotfix ar 1590 revert to old signer

### PR DESCRIPTION
**Pull request by shrinathprabhu**
Resolves [AR-1590](https://team-1624093970686.atlassian.net/browse/AR-1590)

### CODE REVIEW

**Review by ajithranka — APPROVED** [review]
As it's merged on `main`, let's close this PR now.

**Comment by KarthikSiddarth** [comment]
can we change tx-sign.js to transactions-sign.js to increase readability

@ajithranka @shrinathprabhu

**Comment by shrinathprabhu** [comment]
> can we change tx-sign.js to transactions-sign.js to increase readability
> 
> @ajithranka @shrinathprabhu

Yeah will do it on beta

**Comment by shrinathprabhu** [comment]
Closing this PR

**Pull request closed without merging**
