### PR TITLE
AR-869 App Name design fix while creating the app

### PR DESCRIPTION
**Pull request by shrinathprabhu**
Ticket [AR-869](https://team-1624093970686.atlassian.net/browse/AR-869?atlOrigin=eyJpIjoiMzg5NDBiYTQ2MjllNDIwM2FlMDE2NmRmZDM2ZWYxNDgiLCJwIjoiaiJ9)
Adjusted spacing between app name and its input field to make it more visible

### CODE REVIEW

**Review by ajithranka — COMMENTED** [review]
This change looks good but I'm not sure if it's sufficient for making the input visible.

Should we also consider adding some placeholder text and setting autofocus?

```html
<input ... autofocus placeholder="Enter app name" />
```

Screenshot 2022-01-03 at 4 50 28 PM

**Review by mmjee — APPROVED** [review]
LGTM, and +1 for the placeholder text.

**Comment by shrinathprabhu** [comment]
I agree on placeholder text. But for the autofocus part I was just checking and found out that it might confuse people using screen reading technology and so, because the reader will skip the content before the focused element and will just read the label of the textfield, so visually impaired or less sighted people will not have context of why it is used

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#accessibility_considerations

> This change looks good but I'm not sure if it's sufficient for making the input visible.
> 
> Should we also consider adding some placeholder text and setting autofocus?
> 
> ```
> <input ... autofocus placeholder="Enter app name" />
> ```
> 
> Screenshot 2022-01-03 at 4 50 28 PM

**Comment by ajithranka** [comment]
Good catch, @shrinathprabhu. Let's skip the autofocus in that case.

**Review by ajithranka — APPROVED** [review]

**Pull request merged**
